basePath: /
definitions:
  controllers.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  controllers.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  group.AddGroupRequest:
    properties:
      member_ids:
        items:
          type: integer
        type: array
      name:
        type: string
      product_id:
        type: integer
    required:
    - name
    - product_id
    type: object
  models.Group:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.User'
        type: array
      name:
        description: e.g., "Friday Lunch Group"
        type: string
      productID:
        description: FK to Product
        type: integer
      updatedAt:
        type: string
    type: object
  models.Product:
    properties:
      category:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: integer
      imageURL:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      updatedAt:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updatedAt:
        type: string
    type: object
  responses.ProductResponse:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  responses.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  utils.CustomError:
    properties:
      code:
        type: integer
      details:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation
  title: GoShare API
  version: "1.0"
paths:
  /addProduct:
    post:
      consumes:
      - application/json
      description: Create a new product and store it in the database.
      parameters:
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created product
          schema:
            $ref: '#/definitions/responses.ProductResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Database error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Add a new product
      tags:
      - products
  /groups:
    post:
      consumes:
      - application/json
      description: Add a new group with an optional list of member user IDs.
      parameters:
      - description: Group data
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/group.AddGroupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Group'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Create a new group
      tags:
      - groups
  /groups/{id}:
    get:
      description: Retrieve a specific group order by its ID
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Group data
          schema:
            $ref: '#/definitions/models.Group'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/utils.CustomError'
        "404":
          description: Group not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Database error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Get a group by ID
      tags:
      - groups
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with email and password, generates a JWT,
        sets it as an HTTP-only cookie, and returns a success response.
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User logged in successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body or user does not exist
          schema:
            $ref: '#/definitions/utils.CustomError'
        "401":
          description: Invalid password
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Log in a user
      tags:
      - auth
  /me:
    get:
      description: Retrieve the profile information of the currently authenticated
        user.
      produces:
      - application/json
      responses:
        "200":
          description: User profile data
          schema:
            $ref: '#/definitions/responses.UserResponse'
        "401":
          description: Unauthorized, invalid or missing token
          schema:
            $ref: '#/definitions/utils.CustomError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Database error
          schema:
            $ref: '#/definitions/utils.CustomError'
      security:
      - ApiKeyAuth: []
      summary: Get current authenticated user profile
      tags:
      - users
  /ping:
    get:
      description: Check if the server is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
  /product/{id}:
    get:
      description: Retrieve product info by id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product data
          schema:
            $ref: '#/definitions/responses.ProductResponse'
        "404":
          description: product not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: database error
          schema:
            $ref: '#/definitions/utils.CustomError'
      security:
      - ApiKeyAuth: []
      summary: Get product information
      tags:
      - products
  /products:
    get:
      description: Retrieve all products from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.ProductResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - products
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with name, email, and password. Password
        is hashed before storing.
      parameters:
      - description: Registration data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid registration data or user already exists
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: Database error or password hashing failed
          schema:
            $ref: '#/definitions/utils.CustomError'
      summary: Register a new user
      tags:
      - auth
  /user/{id}:
    get:
      description: Retrieve user details by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/responses.UserResponse'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/utils.CustomError'
        "500":
          description: database error
          schema:
            $ref: '#/definitions/utils.CustomError'
      security:
      - ApiKeyAuth: []
      summary: Get user information
      tags:
      - users
swagger: "2.0"
